import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { QueryProvider } from "@/Providers/queryProvider";
import { ThemeProvider } from "@/Providers/themeProvider";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  
  return (

    <html lang="en" suppressHydrationWarning>
      <QueryProvider>
        
      <body>
        <ThemeProvider     attribute="class"
      defaultTheme="system"
      enableSystem
      disableTransitionOnChange>
        {children}

        </ThemeProvider>
      </body>
      
      </QueryProvider>
    </html>
 
  );
}
